# Generated by Django 5.2 on 2025-05-06 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='faculty',
            field=models.CharField(choices=[('CIT', 'CIT'), ('BUS', 'Business'), ('ENGINEERING', 'Engineering'), ('SOCIAL_SCIENCES', 'Social Sciences'), ('MEDIA', 'Media & Communication'), ('SCI_TECH', 'Science & Technology')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='election',
            name='faculty',
            field=models.CharField(choices=[('CIT', 'CIT'), ('BUS', 'Business'), ('ENGINEERING', 'Engineering'), ('SOCIAL_SCIENCES', 'Social Sciences'), ('MEDIA', 'Media & Communication'), ('SCI_TECH', 'Science & Technology')], max_length=30),
        ),
    ]
