# Generated by Django 5.2 on 2025-05-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidate_faculty_alter_candidate_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='allowed_candidates',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of candidates a student can vote for in this election'),
        ),
    ]
