# Generated by Django 5.2 on 2025-05-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_election_allowed_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='block_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Block Number'),
        ),
        migrations.AddField(
            model_name='vote',
            name='from_address',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='From Wallet Address'),
        ),
        migrations.AddField(
            model_name='vote',
            name='gas_used',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Gas Used'),
        ),
        migrations.AddField(
            model_name='vote',
            name='to_address',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='To (Contract) Address'),
        ),
        migrations.AddField(
            model_name='vote',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True, verbose_name='Transaction Hash'),
        ),
        migrations.AddField(
            model_name='vote',
            name='tx_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Transaction Successful'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='faculty',
            field=models.CharField(choices=[('CIT', 'CIT'), ('BUS', 'Business'), ('ENG', 'Engineering'), ('FSS', 'Social Sciences'), ('MMC', 'Media & Communication'), ('FST', 'Science & Technology')], max_length=30),
        ),
        migrations.AlterField(
            model_name='election',
            name='faculty',
            field=models.CharField(choices=[('CIT', 'CIT'), ('BUS', 'Business'), ('ENG', 'Engineering'), ('FSS', 'Social Sciences'), ('MMC', 'Media & Communication'), ('FST', 'Science & Technology')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidates',
            field=models.ManyToManyField(editable=False, to='core.candidate'),
        ),
    ]
