# Generated by Django 5.2 on 2025-05-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='reg_no',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
