# Generated by Django 5.2 on 2025-05-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('CIT', 'CIT'), ('FST', 'FST'), ('FSS', 'FSS'), ('BUS', 'BUS'), ('ENG', 'ENG'), ('MMC', 'MMC')], max_length=10, unique=True)),
            ],
        ),
    ]
